### ISSUE TITLE
Getting 401 error

### ISSUE THREAD

**Issue by saibalfb** [austenstone/openai-completion-action#26]
I have cloned your code in my repo and run the main.yaml with GitHub actions, after entering the text string "write an ice cream shop name." on prompt getting "Error: Error: Request failed with status code 401" in the run.
Can you please help me to know what I am doing wrong?
Thanks
Saibal

**Comment by austenstone** [comment]
401 is unauthorized.

You need to provide:
[OpenAI API Key](https://beta.openai.com/account/api-keys) as an enviroment variable called `OPENAI_API_KEY`.

[example](https://github.com/austenstone/openai-completion-action/actions/runs/2656533065/workflow#L22-L23)

**Comment by austenstone** [comment]
BTW the answer is [`The Sweet Spot`](https://github.com/austenstone/openai-completion-action/runs/7909846843?check_suite_focus=true#step:4:11)
